version: '3'

volumes:
  mysql_data:
      driver: local

services:
  mysql:
      image: mysql:5.7
      volumes:
        - mysql_data:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: keycloak
        MYSQL_USER: keycloak
        MYSQL_PASSWORD: password
      ports:
        - '3306:3306'
      expose:
        - '3306'
  keycloak:
      image: quay.io/keycloak/keycloak:legacy
      environment:
        DB_VENDOR: MYSQL
        DB_ADDR: mysql
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: Pa55w0rd
      ports:
        - 8085:8080
      depends_on:
        - mysql
  react-frontend:
      container_name: reactjs-frontend
      stdin_open: true
      build:
        context: .
        dockerfile: Dockerfile
      command: npm run start
      expose:
        - 3000
      ports:
        - "3000:3000"
      volumes: 
          - /app/node_modules
          - .:/app
     