FROM node:13.12.0-alpine
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json ./app
COPY package-lock.json ./app
RUN npm install --silent
RUN npm install react-scripts@4.0.3 -g --silent
COPY . ./

EXPOSE 3000
CMD ["npm", "run", "start"]